-- src/meta/itemMeta.lua
--
-- GENERATED by `lua generate.lua meta`. Do not edit by hand.
--
-- Derived from Questie's itemKeys and itemCompilerTypes. The key enum keeps deriving because
-- each data file carries its own copy; the compiler-type column is
-- materialized here because Questie's copy dies with the compiler.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Item',
  metaPrefix = 'Item-',
  fieldCount = 16,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    ['name'] = 1,
    ['npcDrops'] = 2,
    ['objectDrops'] = 3,
    ['itemDrops'] = 4,
    ['startQuest'] = 5,
    ['questRewards'] = 6,
    ['flags'] = 7,
    ['foodType'] = 8,
    ['itemLevel'] = 9,
    ['requiredLevel'] = 10,
    ['ammoType'] = 11,
    ['class'] = 12,
    ['subClass'] = 13,
    ['vendors'] = 14,
    ['relatedQuests'] = 15,
    ['teachesSpell'] = 16,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='npcDrops', [3]='objectDrops', [4]='itemDrops', [5]='startQuest', [6]='questRewards', [7]='flags', [8]='foodType', [9]='itemLevel', [10]='requiredLevel', [11]='ammoType', [12]='class', [13]='subClass', [14]='vendors', [15]='relatedQuests', [16]='teachesSpell'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='table', [3]='table', [4]='table', [5]='number', [6]='table', [7]='number', [8]='number', [9]='number', [10]='number', [11]='number', [12]='number', [13]='number', [14]='table', [15]='table', [16]='number'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[2]='idarray', [3]='idarray', [4]='idarray', [6]='idarray', [14]='idarray', [15]='idarray'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='u16u24array', [3]='u8u24array', [4]='u8u24array', [5]='u24', [6]='u8u24array', [7]='u32', [8]='u8', [9]='u16', [10]='u8', [11]='u8', [12]='u8', [13]='u8', [14]='u16u24array', [15]='u8u24array', [16]='u24'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[2]=true, [3]=true, [4]=true, [6]=true, [14]=true, [15]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {

  },

  --- fieldIndex -> named normalizer
  normalize = {

  },

  --- field indices carrying translations
  l10nFields = {1},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Item'] = meta
end

return meta
