-- src/meta/npcMeta.lua
--
-- GENERATED by `lua generate.lua meta`. Do not edit by hand.
--
-- Derived from Questie's npcKeys and npcCompilerTypes. The key enum keeps deriving because
-- each data file carries its own copy; the compiler-type column is
-- materialized here because Questie's copy dies with the compiler.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Npc',
  metaPrefix = 'Npc-',
  fieldCount = 15,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    ['name'] = 1,
    ['minLevelHealth'] = 2,
    ['maxLevelHealth'] = 3,
    ['minLevel'] = 4,
    ['maxLevel'] = 5,
    ['rank'] = 6,
    ['spawns'] = 7,
    ['waypoints'] = 8,
    ['zoneID'] = 9,
    ['questStarts'] = 10,
    ['questEnds'] = 11,
    ['factionID'] = 12,
    ['friendlyToFaction'] = 13,
    ['subName'] = 14,
    ['npcFlags'] = 15,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='minLevelHealth', [3]='maxLevelHealth', [4]='minLevel', [5]='maxLevel', [6]='rank', [7]='spawns', [8]='waypoints', [9]='zoneID', [10]='questStarts', [11]='questEnds', [12]='factionID', [13]='friendlyToFaction', [14]='subName', [15]='npcFlags'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='number', [3]='number', [4]='number', [5]='number', [6]='number', [7]='table', [8]='table', [9]='number', [10]='table', [11]='table', [12]='number', [13]='string', [14]='string', [15]='number'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[7]='spawnlist', [8]='waypointlist', [10]='idarray', [11]='idarray'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='u32', [3]='u32', [4]='u8', [5]='u8', [6]='u8', [7]='spawnlist', [8]='waypointlist', [9]='u16', [10]='u8u24array', [11]='u8u24array', [12]='u16', [13]='faction', [14]='u8string', [15]='u32'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[7]=true, [8]=true, [10]=true, [11]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {

  },

  --- fieldIndex -> named normalizer
  normalize = {
[13]='faction'
  },

  --- fieldIndex -> placeholder returned without storing per-entity metadata
  constantValues = {
[2]=0, [3]=1
  },

  --- field indices carrying translations
  l10nFields = {1,14},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Npc'] = meta
end

return meta
