-- src/meta/objectMeta.lua
--
-- GENERATED by `lua generate.lua meta`. Do not edit by hand.
--
-- Derived from Questie's objectKeys and objectCompilerTypes. The key enum keeps deriving because
-- each data file carries its own copy; the compiler-type column is
-- materialized here because Questie's copy dies with the compiler.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Object',
  metaPrefix = 'Object-',
  fieldCount = 7,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    ['name'] = 1,
    ['questStarts'] = 2,
    ['questEnds'] = 3,
    ['spawns'] = 4,
    ['zoneID'] = 5,
    ['factionID'] = 6,
    ['waypoints'] = 7,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='questStarts', [3]='questEnds', [4]='spawns', [5]='zoneID', [6]='factionID', [7]='waypoints'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='table', [3]='table', [4]='table', [5]='number', [6]='number', [7]='table'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[2]='idarray', [3]='idarray', [4]='spawnlist', [7]='waypointlist'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='u8u24array', [3]='u8u24array', [4]='spawnlist', [5]='u16', [6]='u16', [7]='waypointlist'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[2]=true, [3]=true, [4]=true, [7]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {

  },

  --- fieldIndex -> named normalizer
  normalize = {

  },

  --- field indices carrying translations
  l10nFields = {1},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Object'] = meta
end

return meta
