-- src/meta/questMeta.lua
--
-- GENERATED by `lua generate.lua meta`. Do not edit by hand.
--
-- Derived from Questie's questKeys and questCompilerTypes. The key enum keeps deriving because
-- each data file carries its own copy; the compiler-type column is
-- materialized here because Questie's copy dies with the compiler.

local _, LibQuestieDB = ...

local meta = {
  entity = 'Quest',
  metaPrefix = 'Quest-',
  fieldCount = 36,

  --- fieldName -> fieldIndex. The Database Key Enum.
  keys = {
    ['name'] = 1,
    ['startedBy'] = 2,
    ['finishedBy'] = 3,
    ['requiredLevel'] = 4,
    ['questLevel'] = 5,
    ['requiredRaces'] = 6,
    ['requiredClasses'] = 7,
    ['objectivesText'] = 8,
    ['triggerEnd'] = 9,
    ['objectives'] = 10,
    ['sourceItemId'] = 11,
    ['preQuestGroup'] = 12,
    ['preQuestSingle'] = 13,
    ['childQuests'] = 14,
    ['inGroupWith'] = 15,
    ['exclusiveTo'] = 16,
    ['zoneOrSort'] = 17,
    ['requiredSkill'] = 18,
    ['requiredMinRep'] = 19,
    ['requiredMaxRep'] = 20,
    ['requiredSourceItems'] = 21,
    ['nextQuestInChain'] = 22,
    ['questFlags'] = 23,
    ['specialFlags'] = 24,
    ['parentQuest'] = 25,
    ['reputationReward'] = 26,
    ['breadcrumbForQuestId'] = 27,
    ['breadcrumbs'] = 28,
    ['extraObjectives'] = 29,
    ['requiredSpell'] = 30,
    ['requiredSpecialization'] = 31,
    ['requiredMaxLevel'] = 32,
    ['availableUntilCompleted'] = 33,
    ['availableStartingWith'] = 34,
    ['requiredRanks'] = 35,
    ['disabledByQuest'] = 36,
  },

  --- fieldIndex -> fieldName
  names = {
[1]='name', [2]='startedBy', [3]='finishedBy', [4]='requiredLevel', [5]='questLevel', [6]='requiredRaces', [7]='requiredClasses', [8]='objectivesText', [9]='triggerEnd', [10]='objectives', [11]='sourceItemId', [12]='preQuestGroup', [13]='preQuestSingle', [14]='childQuests', [15]='inGroupWith', [16]='exclusiveTo', [17]='zoneOrSort', [18]='requiredSkill', [19]='requiredMinRep', [20]='requiredMaxRep', [21]='requiredSourceItems', [22]='nextQuestInChain', [23]='questFlags', [24]='specialFlags', [25]='parentQuest', [26]='reputationReward', [27]='breadcrumbForQuestId', [28]='breadcrumbs', [29]='extraObjectives', [30]='requiredSpell', [31]='requiredSpecialization', [32]='requiredMaxLevel', [33]='availableUntilCompleted', [34]='availableStartingWith', [35]='requiredRanks', [36]='disabledByQuest'
  },

  --- fieldIndex -> storage type: number | string | table
  types = {
[1]='string', [2]='table', [3]='table', [4]='number', [5]='number', [6]='number', [7]='number', [8]='table', [9]='table', [10]='table', [11]='number', [12]='table', [13]='table', [14]='table', [15]='table', [16]='table', [17]='number', [18]='table', [19]='table', [20]='table', [21]='table', [22]='number', [23]='number', [24]='number', [25]='number', [26]='table', [27]='number', [28]='table', [29]='table', [30]='number', [31]='number', [32]='number', [33]='number', [34]='number', [35]='table', [36]='number'
  },

  --- fieldIndex -> structural shape, for validators. nil for scalars.
  structures = {
[2]='questgivers', [3]='questgivers', [8]='stringarray', [9]='trigger', [10]='objectives', [12]='idarray', [13]='idarray', [14]='idarray', [15]='idarray', [16]='idarray', [18]='pair', [19]='pair', [20]='pair', [21]='idarray', [26]='pairs', [28]='idarray', [29]='extraobjectives', [35]='pairs'
  },

  --- fieldIndex -> Questie compiler type. Materialized provenance.
  compilerTypes = {
[1]='u8string', [2]='questgivers', [3]='questgivers', [4]='u8', [5]='s16', [6]='u32', [7]='u16', [8]='u8u16stringarray', [9]='trigger', [10]='objectives', [11]='u24', [12]='u8s24array', [13]='u8u24array', [14]='u8u24array', [15]='u8u24array', [16]='u8u24array', [17]='s16', [18]='u12pair', [19]='s24pair', [20]='s24pair', [21]='u8u24array', [22]='u24', [23]='u24', [24]='u16', [25]='u24', [26]='u8s24pairs', [27]='u24', [28]='u8u24array', [29]='extraobjectives', [30]='s24', [31]='u24', [32]='u8', [33]='u24', [34]='u24', [35]='u8s24pairs', [36]='u24'
  },

  --- fieldIndex -> true when an empty table must read back as nil
  emptyIsNil = {
[2]=true, [3]=true, [8]=true, [9]=true, [10]=true, [12]=true, [13]=true, [14]=true, [15]=true, [16]=true, [18]=true, [19]=true, [20]=true, [21]=true, [26]=true, [28]=true, [29]=true, [35]=true
  },

  --- fieldIndex -> true when {0,0} must read back as nil
  zeroPairIsNil = {
[18]=true, [19]=true, [20]=true
  },

  --- fieldIndex -> named normalizer
  normalize = {

  },

  --- field indices carrying translations
  l10nFields = {1,8},
}

if LibQuestieDB then
  LibQuestieDB.Meta = LibQuestieDB.Meta or {}
  LibQuestieDB.Meta['Quest'] = meta
end

return meta
