#!/usr/bin/env lua
-- generate.lua
--
-- Turns raw entity data plus Static Corrections into a TOC metadata store.
--
-- Usage:
--   lua generate.lua meta                 materialize src/meta/*Meta.lua from Questie's schema
--   lua generate.lua all                  every flavor
--   lua generate.lua Vanilla [TBC ...]    named flavors
--
-- Options:
--   --types=Quest,Npc      restrict entity types
--   --fields=name,zoneOrSort   restrict fields (tracer-bullet slices only)
--   --quiet
--
-- Runs on a plain Lua 5.1 interpreter. No `lfs`, no other C dependency — inputs are
-- enumerated in src/config.lua rather than discovered by scanning directories, which keeps
-- the option of shipping a bare `lua` binary for contributors.

local config = dofile("src/config.lua")
local lib = dofile("generator/lib.lua")
local loader = dofile("generator/loader.lua")
local schema = dofile("generator/schema.lua")
local encode = dofile("generator/encode.lua")
local corrections = dofile("generator/corrections.lua")

local generate = {}

--------------------------------------------------------------------------------------------
-- Arguments
--------------------------------------------------------------------------------------------

local function parseArgs(argv)
  local opts = { flavors = {}, types = nil, fields = nil, quiet = false, target = nil }
  for _, value in ipairs(argv) do
    local key, val = value:match("^%-%-([%w%-]+)=(.*)$")
    if key == "types" then
      opts.types = {}
      for name in val:gmatch("[^,]+") do opts.types[name] = true end
    elseif key == "fields" then
      opts.fields = {}
      for name in val:gmatch("[^,]+") do opts.fields[name] = true end
    elseif value == "--quiet" then
      opts.quiet = true
    elseif value:sub(1, 2) == "--" then
      error("Unknown option: " .. value, 0)
    elseif value == "meta" or value == "all" then
      opts.target = value
    else
      opts.flavors[#opts.flavors + 1] = value
    end
  end
  return opts
end

local QUIET = false
local function say(...)
  if not QUIET then print(...) end
end

--------------------------------------------------------------------------------------------
-- Schema materialization
--------------------------------------------------------------------------------------------

--- Derive the schema from Questie's `*Keys` and `*CompilerTypes` and write src/meta/*Meta.lua.
---
--- Questie's schema files are the only source of `*CompilerTypes`, and they die with the
--- compiler. Materializing captures the type map before it disappears; the key enum keeps
--- deriving afterwards because every data file carries its own copy.
function generate.materializeMeta(questiePath)
  questiePath = questiePath or "../Questie"
  lib.mkdirp("src/meta")

  for _, entityType in ipairs(config.entityTypes) do
    local schemaFile = questiePath .. "/Database/" .. entityType.name:lower() .. "DB.lua"
    if not lib.fileExists(schemaFile) then
      error("Cannot derive schema: " .. schemaFile .. " not found. Pass the path to a Questie " ..
            "checkout as the second argument.", 0)
    end
    local keys, compilerTypes = loader.loadSchemaFile(schemaFile, entityType, { isClassic = true, expansion = 1 })
    local meta = schema.derive(entityType, keys, compilerTypes)

    -- Cross-check against every flavor's data file, since the key enum travels with the data.
    for _, flavor in ipairs(config.flavors) do
      local dataPath = config.dataPath(flavor, entityType)
      if lib.fileExists(dataPath) then
        local entities, dataKeys = loader.loadEntityData(dataPath, entityType)
        local omitted = schema.checkKeys(meta, dataKeys, dataPath)
        schema.assertNoDataBeyondKeys(meta, entities, dataKeys, dataPath)
        for name, index in pairs(omitted) do
          say(string.format("  note: %s omits '%s' (field %d) — no row in that file uses it",
            dataPath, name, index))
        end
      end
    end

    local path = schema.metaPath(entityType)
    lib.writeAll(path, schema.render(meta))
    say(string.format("Materialized %s (%d fields)", path, meta.fieldCount))
  end
end

--------------------------------------------------------------------------------------------
-- TOC emission
--------------------------------------------------------------------------------------------

local BUILD

local function writeHeader(out, flavor, fileList)
  out:write("# GENERATED by `lua generate.lua ", flavor.name, "`. Do not edit, do not commit.\n")
  out:write("# Baked mode: entity reads resolve from the TOC metadata store below.\n")
  out:write("## Interface: ", flavor.interface, "\n")
  out:write("## Title: QuestieTDB\n")
  out:write("## Notes: The database Questie consumes.\n")
  out:write("## Author: Questie contributors\n")
  out:write("## Version: 0.0.0\n")
  out:write("## X-Contract-Version: ", tostring(config.contractVersion), "\n")
  out:write("## X-Flavor: ", flavor.name, "\n")
  out:write("## X-Mode: baked\n")
  out:write("## X-BUILD-COMMIT: ", BUILD.commit, "\n")
  out:write("## X-BUILD-TIME: ", BUILD.time, "\n")
  out:write("\n")
  for _, file in ipairs(fileList) do
    out:write(file:gsub("/", "\\"), "\n")
  end
  out:write("\n")
end

local function bakedFileList()
  local files = {}
  for _, file in ipairs(config.runtimeFiles.shared) do files[#files + 1] = file end
  files[#files + 1] = config.runtimeFiles.bakedReader
  for _, file in ipairs(config.runtimeFiles.tail) do files[#files + 1] = file end
  return files
end

--- Emit every metadata line for one entity type.
---@return number entityCount
---@return number fieldCount
---@return number lineCount
local function writeEntityMetadata(out, meta, entities, fieldFilter)
  local ids = lib.sortedIds(entities)
  local fieldCount, lineCount = 0, 0
  local prefix = "X-" .. meta.metaPrefix

  for _, id in ipairs(ids) do
    local row = entities[id]
    local key = prefix .. id .. "-"
    for fieldIndex = 1, meta.fieldCount do
      if not fieldFilter or fieldFilter[meta.names[fieldIndex]] then
        local ok, encoded = pcall(encode.field, meta, fieldIndex, row[fieldIndex])
        if not ok then
          error(string.format("%s id %d: %s", meta.entity, id, tostring(encoded)), 0)
        end
        if encoded ~= nil then
          lineCount = lineCount + lib.writeMetadata(out, key .. fieldIndex, encoded, config.maxValueLength)
          fieldCount = fieldCount + 1
        end
      end
    end
  end

  lineCount = lineCount + lib.writeMetadata(out, prefix .. "IDS-LIST", encode.idList(ids), config.maxValueLength)
  return #ids, fieldCount, lineCount
end

--------------------------------------------------------------------------------------------
-- Driver
--------------------------------------------------------------------------------------------

--- Load every entity type for one flavor, apply Static Corrections, and return the tables.
function generate.loadFlavor(flavor, typeFilter, applyCorrections)
  local loaded = {}
  for _, entityType in ipairs(config.entityTypes) do
    if not typeFilter or typeFilter[entityType.name] then
      local path = config.dataPath(flavor, entityType)
      local entities, keys = loader.loadEntityData(path, entityType)
      local meta = schema.loadMaterialized(entityType)
      schema.checkKeys(meta, keys, path)
      schema.assertNoDataBeyondKeys(meta, entities, keys, path)
      loaded[entityType.name] = { meta = meta, entities = entities, path = path }
    end
  end

  if applyCorrections ~= false then
    corrections.applyStatic(loaded, flavor)
  end

  return loaded
end

function generate.flavor(flavor, opts)
  local started = os.clock()
  local loaded = generate.loadFlavor(flavor, opts.types)

  local tocPath = config.tocPath(flavor)
  local out = assert(io.open(tocPath, "wb"), "Cannot write " .. tocPath)
  writeHeader(out, flavor, bakedFileList())

  local totals = { entities = 0, fields = 0, lines = 0 }
  for _, entityType in ipairs(config.entityTypes) do
    local entry = loaded[entityType.name]
    if entry then
      local entities, fields, lines = writeEntityMetadata(out, entry.meta, entry.entities, opts.fields)
      totals.entities = totals.entities + entities
      totals.fields = totals.fields + fields
      totals.lines = totals.lines + lines
      say(string.format("  %-7s %6d entities  %8d fields", entityType.name, entities, fields))
    end
  end

  out:close()

  local size = #lib.readAll(tocPath)
  say(string.format("Generated %s — %d entities, %d fields, %.1f MB, %.1fs",
    tocPath, totals.entities, totals.fields, size / 1048576, os.clock() - started))
  return totals
end

--------------------------------------------------------------------------------------------
-- Entry point
--------------------------------------------------------------------------------------------

local opts = parseArgs(arg or {})
QUIET = opts.quiet
BUILD = { commit = lib.gitCommit(), time = lib.buildTime() }

if opts.target == "meta" then
  generate.materializeMeta(opts.flavors[1])
  os.exit(0)
end

local flavors = {}
if opts.target == "all" or #opts.flavors == 0 then
  flavors = config.flavors
else
  for _, name in ipairs(opts.flavors) do
    local flavor = config.flavorByName[name]
    if not flavor then
      error("Unknown flavor: " .. name .. ". Known: Vanilla, TBC, Wrath, Cata, Mists", 0)
    end
    flavors[#flavors + 1] = flavor
  end
end

for _, flavor in ipairs(flavors) do
  generate.flavor(flavor, opts)
end
