---@meta _

---@class QuestDB
---@field name fun(id: QuestieTDBQuestId): string? Quest name.
---@field startedBy fun(id: QuestieTDBQuestId): QuestieTDBStartedBy? Quest starters. Existing quests return a table, even when empty.
---@field finishedBy fun(id: QuestieTDBQuestId): QuestieTDBFinishedBy? Quest finishers. Existing quests return a table, even when empty.
---@field requiredLevel fun(id: QuestieTDBQuestId): number? Minimum player level.
---@field questLevel fun(id: QuestieTDBQuestId): number? Quest level.
---@field requiredRaces fun(id: QuestieTDBQuestId): number? Race bitmask.
---@field requiredClasses fun(id: QuestieTDBQuestId): number? Class bitmask.
---@field objectivesText fun(id: QuestieTDBQuestId): string[]? Objective text lines.
---@field triggerEnd fun(id: QuestieTDBQuestId): QuestieTDBTrigger? Completion trigger.
---@field objectives fun(id: QuestieTDBQuestId): QuestieTDBObjectives? Objective tuples. Existing quests return a table, even when empty.
---@field sourceItemId fun(id: QuestieTDBQuestId): QuestieTDBItemId? Item provided by the quest starter.
---@field preQuestGroup fun(id: QuestieTDBQuestId): QuestieTDBQuestId[]? Group prerequisites.
---@field preQuestSingle fun(id: QuestieTDBQuestId): QuestieTDBQuestId[]? Alternative single prerequisites.
---@field childQuests fun(id: QuestieTDBQuestId): QuestieTDBQuestId[]? Quests unlocked by this quest.
---@field inGroupWith fun(id: QuestieTDBQuestId): QuestieTDBQuestId[]? Quests in the same group.
---@field exclusiveTo fun(id: QuestieTDBQuestId): QuestieTDBQuestId[]? Mutually exclusive quests.
---@field zoneOrSort fun(id: QuestieTDBQuestId): number? Positive area ID or negative quest-sort ID.
---@field requiredSkill fun(id: QuestieTDBQuestId): QuestieTDBSkillPair? Required profession and skill value.
---@field requiredMinRep fun(id: QuestieTDBQuestId): QuestieTDBReputationPair? Minimum reputation requirement.
---@field requiredMaxRep fun(id: QuestieTDBQuestId): QuestieTDBReputationPair? Maximum reputation requirement.
---@field requiredSourceItems fun(id: QuestieTDBQuestId): QuestieTDBItemId[]? Items needed to start the quest.
---@field nextQuestInChain fun(id: QuestieTDBQuestId): QuestieTDBQuestId? Next quest in the chain.
---@field questFlags fun(id: QuestieTDBQuestId): number? Quest flag bitmask.
---@field specialFlags fun(id: QuestieTDBQuestId): number? Special flag bitmask.
---@field parentQuest fun(id: QuestieTDBQuestId): QuestieTDBQuestId? Parent quest.
---@field reputationReward fun(id: QuestieTDBQuestId): QuestieTDBReputationPair[]? Reputation rewards.
---@field breadcrumbForQuestId fun(id: QuestieTDBQuestId): QuestieTDBQuestId? Quest this breadcrumb leads to.
---@field breadcrumbs fun(id: QuestieTDBQuestId): QuestieTDBQuestId[]? Breadcrumbs that lead to this quest.
---@field extraObjectives fun(id: QuestieTDBQuestId): QuestieTDBExtraObjective[]? Hidden special objectives.
---@field requiredSpell fun(id: QuestieTDBQuestId): number? Required spell ID.
---@field requiredSpecialization fun(id: QuestieTDBQuestId): number? Required profession specialization.
---@field requiredMaxLevel fun(id: QuestieTDBQuestId): number? Maximum player level.
---@field availableUntilCompleted fun(id: QuestieTDBQuestId): QuestieTDBQuestId? Quest that ends availability when completed.
---@field availableStartingWith fun(id: QuestieTDBQuestId): QuestieTDBQuestId? Quest that starts availability while active or completed.
---@field requiredRanks fun(id: QuestieTDBQuestId): QuestieTDBSkillRankPair[]? Alternative profession rank requirements.
---@field disabledByQuest fun(id: QuestieTDBQuestId): QuestieTDBQuestId? Quest that temporarily disables this quest while active.
---@field GetByIndex fun(id: QuestieTDBQuestId, fieldIndex: integer): any Read a field by positional index.
---@field Get fun(id: QuestieTDBQuestId, key: QuestieTDBQuestField|integer): any Read a field by canonical name or index.
---@field GetAll fun(id: QuestieTDBQuestId, keys: (QuestieTDBQuestField|integer)[]): QuestieTDBPackedValues? Read fields into a packed table, or nil for an unknown ID.
---@field GetRaw fun(id: QuestieTDBQuestId, key: QuestieTDBQuestField|integer): any Read base data without Corrections or localization.
---@field Exists fun(id: QuestieTDBQuestId): boolean Test the composed view.
---@field InvalidateCache fun(id?: QuestieTDBQuestId) Drop cached fields for one quest or every quest.
QuestDB = {}

---Returns the composed ID list, or a read-only lookup map when `hashmap` is true.
---@param hashmap? false
---@return QuestieTDBQuestId[] ids
---@overload fun(hashmap: true): table<QuestieTDBQuestId, true>
function QuestDB.GetAllIds(hashmap) end
