-- src/corrections/manifest.lua
--
-- GENERATED by `lua tools/port-corrections.lua`. Do not edit by hand.
--
-- Which correction file provides which functions, and whether each is Static or
-- Dynamic. The classification is declared by the author, never inferred — folder names
-- are not a reliable signal, as `Sod/static/sodItemQuestStartFixes.lua` registering
-- dynamic in the prototype demonstrates.

local _, LibQuestieDB = ...

local manifest = {
  { file = 'Era/classicQuestFixes.lua', module = 'QuestieQuestFixes', datatype = 'Quest', static = {'LoadMissingQuests','Load'}, dynamic = {'LoadFactionFixes'} },
  { file = 'Era/classicNPCFixes.lua', module = 'QuestieNPCFixes', datatype = 'Npc', static = {'Load'}, dynamic = {'LoadFactionFixes'}, parameterized = {'LoadDarkmoonFixes'} },
  { file = 'Era/classicItemFixes.lua', module = 'QuestieItemFixes', datatype = 'Item', static = {'Load'}, dynamic = {'LoadFactionFixes'} },
  { file = 'Era/classicObjectFixes.lua', module = 'QuestieObjectFixes', datatype = 'Object', static = {'Load'}, dynamic = {'LoadFactionFixes'} },
  { file = 'Era/classicQuestReputationFixes.lua', module = 'QuestieClassicQuestReputationFixes', datatype = 'Quest', static = {'Load'}, expansions = {['Classic']=true}, generated = true },
  { file = 'Tbc/tbcQuestFixes.lua', module = 'QuestieTBCQuestFixes', datatype = 'Quest', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 2 },
  { file = 'Tbc/tbcNPCFixes.lua', module = 'QuestieTBCNpcFixes', datatype = 'Npc', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 2, parameterized = {'LoadDarkmoonFixes'} },
  { file = 'Tbc/tbcItemFixes.lua', module = 'QuestieTBCItemFixes', datatype = 'Item', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 2 },
  { file = 'Tbc/tbcObjectFixes.lua', module = 'QuestieTBCObjectFixes', datatype = 'Object', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 2 },
  { file = 'Wotlk/wotlkQuestFixes.lua', module = 'QuestieWotlkQuestFixes', datatype = 'Quest', static = {'Load'}, dynamic = {'LoadFactionFixes','LoadTitanReforgedFixes'}, gatedDynamic = {['LoadTitanReforgedFixes']='TitanReforged'}, minExpansionOrder = 3 },
  { file = 'Wotlk/wotlkNPCFixes.lua', module = 'QuestieWotlkNpcFixes', datatype = 'Npc', static = {'Load','LoadAutomatics'}, dynamic = {'LoadFactionFixes','LoadTitanReforgedFixes'}, gatedDynamic = {['LoadTitanReforgedFixes']='TitanReforged'}, minExpansionOrder = 3 },
  { file = 'Wotlk/wotlkItemFixes.lua', module = 'QuestieWotlkItemFixes', datatype = 'Item', static = {'Load'}, dynamic = {'LoadFactionFixes','LoadTitanReforgedFixes'}, gatedDynamic = {['LoadTitanReforgedFixes']='TitanReforged'}, minExpansionOrder = 3 },
  { file = 'Wotlk/wotlkObjectFixes.lua', module = 'QuestieWotlkObjectFixes', datatype = 'Object', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 3 },
  { file = 'Cata/cataQuestFixes.lua', module = 'CataQuestFixes', datatype = 'Quest', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 4 },
  { file = 'Cata/cataNPCFixes.lua', module = 'CataNpcFixes', datatype = 'Npc', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 4 },
  { file = 'Cata/cataItemFixes.lua', module = 'CataItemFixes', datatype = 'Item', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 4 },
  { file = 'Cata/cataObjectFixes.lua', module = 'CataObjectFixes', datatype = 'Object', static = {'Load'}, dynamic = {'LoadFactionFixes'}, minExpansionOrder = 4 },
  { file = 'MoP/mopQuestFixes.lua', module = 'MopQuestFixes', datatype = 'Quest', static = {'Load'}, dynamic = {'LoadFactionFixes','LoadContentPhaseFixes'}, minExpansionOrder = 5 },
  { file = 'MoP/mopNPCFixes.lua', module = 'MopNpcFixes', datatype = 'Npc', static = {'Load'}, dynamic = {'LoadFactionFixes','LoadContentPhaseFixes'}, minExpansionOrder = 5 },
  { file = 'MoP/mopItemFixes.lua', module = 'MopItemFixes', datatype = 'Item', static = {'Load'}, minExpansionOrder = 5 },
  { file = 'MoP/mopObjectFixes.lua', module = 'MopObjectFixes', datatype = 'Object', static = {'Load'}, dynamic = {'LoadFactionFixes','LoadContentPhaseFixes'}, minExpansionOrder = 5 },
  { file = 'Sod/sodQuestFixes.lua', module = 'SeasonOfDiscovery', datatype = 'Quest', dynamic = {'LoadQuests','LoadFactionQuestFixes'}, expansions = {['Classic']=true} },
  { file = 'Sod/sodNPCFixes.lua', module = 'SeasonOfDiscovery', datatype = 'Npc', dynamic = {'LoadNPCs'}, expansions = {['Classic']=true} },
  { file = 'Sod/sodItemFixes.lua', module = 'SeasonOfDiscovery', datatype = 'Item', dynamic = {'LoadItems'}, expansions = {['Classic']=true} },
  { file = 'Sod/sodObjectFixes.lua', module = 'SeasonOfDiscovery', datatype = 'Object', dynamic = {'LoadObjects'}, expansions = {['Classic']=true} },
  { file = 'Sod/sodBaseQuests.lua', module = 'SeasonOfDiscovery', datatype = 'Quest', dynamic = {'LoadBaseQuests'}, expansions = {['Classic']=true}, generated = true },
  { file = 'Sod/sodBaseNPCs.lua', module = 'SeasonOfDiscovery', datatype = 'Npc', dynamic = {'LoadBaseNPCs'}, expansions = {['Classic']=true}, generated = true },
  { file = 'Sod/sodBaseItems.lua', module = 'SeasonOfDiscovery', datatype = 'Item', dynamic = {'LoadBaseItems'}, expansions = {['Classic']=true}, generated = true },
  { file = 'Sod/sodBaseObjects.lua', module = 'SeasonOfDiscovery', datatype = 'Object', dynamic = {'LoadBaseObjects'}, expansions = {['Classic']=true}, generated = true },
  { file = 'Shared/itemStartFixes.lua', module = 'QuestieItemStartFixes', datatype = 'Item', static = {'LoadAutomaticQuestStarts'}, options = {['noNewEntries']=true,['noOverwrites']=true}, generated = true },
}

if LibQuestieDB then
  LibQuestieDB.CorrectionManifest = manifest
end

return manifest
